routes/web.php
<?php

use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Route::resource('roles', RoleController::class);
    Route::prefix('roles')->middleware('roles:super-admin')->controller(RoleController::Class)->name('roles.')->group(
        function () {
            Route::get('/', 'index')->name('index');
            Route::post('/', 'store')->name('store');
            Route::get('/create', 'create')->name('create');
            Route::get('/{role_id}', 'show')->name('show');
            Route::put('/{role_id}', 'update')->name('update');
            Route::delete('/{role_id}', 'destroy')->name('destroy');
            Route::get('/edit/{role_id}', 'edit')->name('edit');
        }
    );
    // Route::resource('users', UserController::class);
    Route::prefix('users')->controller(UserController::Class)->name('users.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('can:show-user');
        Route::post('/', 'store')->name('store')->middleware('can:create-user');
        Route::get('/create', 'create')->name('create')->middleware('can:create-user');
        Route::get('/{user_id}', 'show')->name('show')->middleware('can:show-user');
        Route::put('/{user_id}', 'update')->name('update')->middleware('can:update-user');
        Route::delete('/{user_id}', 'destroy')->name('destroy')->middleware('can:delete-user');
        Route::get('/edit/{user_id}', 'edit')->name('edit')->middleware('can:update-user');
    });
    // Route::resource('categories', CategoryController::class);
    Route::prefix('categories')->controller(CategoryController::Class)->name('categories.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('can:show-category');
        Route::post('/', 'store')->name('store')->middleware('can:create-category');
        Route::get('/create', 'create')->name('create')->middleware('can:create-category');
        Route::get('/{category_id}', 'show')->name('show')->middleware('can:show-category');
        Route::put('/{category_id}', 'update')->name('update')->middleware('can:update-category');
        Route::delete('/{category_id}', 'destroy')->name('destroy')->middleware('can:delete-category');
        Route::get('/edit/{category_id}', 'edit')->name('edit')->middleware('can:update-category');
    });
    // Route::resource('products', ProductController::class);
    Route::prefix('products')->controller(ProductController::Class)->name('products.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('can:show-product');
        Route::post('/', 'store')->name('store')->middleware('can:create-product');
        Route::get('/create', 'create')->name('create')->middleware('can:create-product');
        Route::get('/{product_id}', 'show')->name('show')->middleware('can:show-product');
        Route::put('/{product_id}', 'update')->name('update')->middleware('can:update-product');
        Route::delete('/{product_id}', 'destroy')->name('destroy')->middleware('can:delete-product');
        Route::get('/edit/{product_id}', 'edit')->name('edit')->middleware('can:update-product');
    });
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
});
Auth::routes();
    Route::controller(ForgotPasswordController::class)->group(function () {
        Route::get('forget-password', 'showForgetPasswordForm')->name('forget.password.get');
        Route::post('forget-password', 'sendMail')->name('forget.password.post');
        Route::get('reset-password/{token}', 'showResetPasswordForm')->name('reset.password.get');
        Route::post('reset-password', 'resetPassword')->name('reset.password.post');
    });

    Route::controller(RegisterController::class)->group(function () {
        Route::get('create-password/{token}','showCreatePasswordForm')->name('create.password.get');
        Route::post('create-password','createPassword')->name('create.password.post');
    });

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'description'];

    public function permissions()
    {
        return $this->belongsToMany(Permission::class,'role_permission','role_id','permission_id');
    }
    public function scopeSearchByName($query, $keyword)
    {
        return $query->where('name', 'like', '%' . $keyword . '%');
    }

    public function scopeSearchByDescription($query, $keyword)
    {
        return $query->where('description', 'like', '%' . $keyword . '%');
    }
    public function scopeSearchByNameAndDes($query, $keyword)
    {
        return $query->searchByName($keyword)->orWhere(function ($query) use ($keyword) {
            $query->searchByDescription($keyword);
        });
    }


}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RoleRequest;
use App\Models\Permission;
use App\Models\Role;
use App\Services\PermissionService;
use App\Services\RoleService;
use App\Services\RoleServiceInterface;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class RoleController extends Controller
{
    private $roleService;
    private $permissionService;

    public function __construct(RoleService $roleService, PermissionService $permissionService)
    {
        $this->roleService = $roleService;
        $this->permissionService = $permissionService;
    }

    public function index(Request $request)
    {
        $keyword = $request->input('keyword', '');
        $roles = $this->roleService->searchRoles($keyword);
        return view('admin.roles.index', compact('roles','keyword'));
    }
    public function create()
    {
        $permissions = $this->permissionService->getPermissionsParent();
        return view('admin.roles.create', compact('permissions'));
    }

    public function store(RoleRequest $request)
    {
        $dataRole = $request->all();
        $this->roleService->createRole($dataRole);
        return redirect()->route('roles.index')->with('success', 'Role created successfully.');
    }

    public function edit($role_id)
    {
        try {
            $this->roleService->getAndCheckRoleById($role_id);
            $data = $this->roleService->getRoleDataForEdit($role_id);
            return view('admin.roles.edit', $data);
        } catch (ModelNotFoundException $e) {
            abort(404, 'Role not found');
        }
    }

    public function update(RoleRequest $request, $role_id)
    {
        try {
            $this->roleService->getAndCheckRoleById($role_id);
            $dataRole = $request->all();
            $this->roleService->updateRole($role_id, $dataRole);
            return redirect()->route('roles.index')->with('success', 'Role updated successfully.');
        } catch (ModelNotFoundException $e) {
            abort(404, 'Role not found');
        }
    }

    public function destroy($role_id)
    {
        try {
            $this->roleService->getAndCheckRoleById($role_id);
            $this->roleService->deleteRole($role_id);
            return response()->json(['success' => true, 'tr' => 'tr_' . $role_id]);
        } catch (ModelNotFoundException $e) {
            abort(404, 'Role not found');
        }
    }

}

resources/views/admin/roles/create.blade.php
@extends('admin.layout')
@section('content')
    <section class="panel">
        <header class="panel-heading">
            Create Role
        </header>
        <div class="panel-body">
            @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            <!-- Add error message -->
            @if(session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="form">
                <form class="cmxform form-horizontal" id="commentForm" enctype="multipart/form-data"
                      method="post" action="{{ route('roles.store') }}" novalidate="novalidate">
                    @csrf
                    <div class="form-group">
                        <label for="cname" class="control-label col-lg-3">Name </label>
                        <div class="col-lg-6">
                            <input class="form-control" id="cname" name="name" minlength="2" type="text"
                                   value=" {{ old('name') }}" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="control-label col-lg-3">Description </label>
                        <div class="col-lg-6">
                            <input class="form-control" id="cemail" type="email" value=" {{ old('description') }}"
                                   name="description" required>
                        </div>
                    </div>
                    <div class="border-dark p-3">
                        <div class="form-group">
                            <div class="col-md-12">
                                <div class="row">
                                    @foreach($permissions as $permissionsParentItem)
                                        <div class="card border-primary mb-3 col-md-12">
                                            <div class="card-header">
                                                <label>
                                                    <input type="checkbox" value="" class="checkbox_wrapper">
                                                </label> Module {{$permissionsParentItem->name}}
                                            </div>
                                            <div class="row">
                                                @foreach($permissionsParentItem->permissionsChildrent as $permissionChildrenItem )
                                                    <div class="card-body text-primary col-md-3">
                                                        <h5 class="card-title">
                                                            <label>
                                                                <input type="checkbox" class="checkbox_children"
                                                                       name="permission_id[]"
                                                                       value="{{$permissionChildrenItem->id}}"
                                                                       @if(is_array(old('permission_id')) && in_array($permissionChildrenItem->id, old('permission_id')))
                                                                           checked
                                                                    @endif
                                                                >
                                                            </label>
                                                            {{$permissionChildrenItem->name}}
                                                        </h5>
                                                    </div>
                                                @endforeach
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-3 col-lg-6">
                            <button class="btn btn-primary" type="submit">Save</button>
                            <button class="btn btn-default" type="button">Cancel</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('admin.layout')
@section('content')
    <section class="panel">
        <header class="panel-heading">
            Edit Role
        </header>
        <div class="panel-body">
            @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            <!-- Add error message -->
            @if(session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>
        <div class="form">
            <form class="cmxform form-horizontal" id="commentForm" method="post"
                  action="{{ route('roles.update',['role_id' => $role->id]) }}" novalidate="novalidate">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="cname" class="control-label col-lg-3">Name </label>
                    <div class="col-lg-6">
                        <input class="form-control" id="cname" name="name" minlength="2" type="text"
                               value="{{ old('name', $role->name) }}" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="control-label col-lg-3">Description </label>
                    <div class="col-lg-6">
                        <input class="form-control" id="cemail" type="email" name="description"
                               value="{{ old('description', $role->description) }}" required>
                    </div>
                </div>
                <div class="border-dark p-3">
                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="row">
                                @foreach($permissionsParent as $permissionsParentItem)
                                    <div class="card border-primary mb-3 col-md-12">
                                        <div class="card-header">
                                            <label>
                                                <input type="checkbox" value="" class="checkbox_wrapper">
                                            </label> Module {{$permissionsParentItem->name}}
                                        </div>
                                        <div class="row">
                                            @foreach($permissionsParentItem->permissionsChildrent as $permissionChildrenItem)
                                                <div class="card-body text-primary col-md-3">
                                                    <h5 class="card-title">
                                                        <label>
                                                            <input type="checkbox" class="checkbox_children"
                                                                   name="permission_id[]"
                                                                   {{ (collect(old('permission_id', $permissionChecked->pluck('id')))->contains($permissionChildrenItem->id)) ? 'checked' : '' }}
                                                                   value="{{ $permissionChildrenItem->id }}">
                                                        </label>
                                                        {{ $permissionChildrenItem->name }}
                                                    </h5>
                                                </div>
                                            @endforeach
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-offset-3 col-lg-6">
                        <button class="btn btn-primary" type="submit">Save</button>
                        <button class="btn btn-default" type="button">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
        </div>
    </section>
@endsection

resources/views/admin/roles/index.blade.php
@extends('admin.layout')
@section('content')

    <section class="wrapper">
        <div class="table-agile-info">
            <div class="panel panel-default">
                <div class="panel-heading">
                    List Roles
                </div>
                <div class="row w3-res-tb">
                    <div class="col-sm-4">
                    </div>
                    <div class="col-sm-3 search-key">
                        <div class="input-group">
                            <form action="{{ route('roles.index') }}" method="GET">
                                <input type="text" class="input-sm form-control" placeholder="Search" name="keyword"
                                       value="{{ $keyword }}">
                                <div class="input-group-btn">
                                    <button class="btn btn-sm btn-default" type="submit">Search</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                @if ($roles->isEmpty())
                    <div class="alert alert-info">
                        Not have data for keyword: {{ $keyword }}
                    </div>
                @else
                    <div class="table-responsive">
                        @if(session()->has('success'))
                            <div class="alert alert-success">
                                {{ session('success') }}
                            </div>
                        @endif

                        @if(session()->has('error'))
                            <div class="alert alert-danger">
                                {{ session('error') }}
                            </div>
                        @endif

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <table class="table table-striped b-t b-light">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th style="width: 30px;"></th>
                                <th style="width: 30px;"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($roles as $role)
                                <tr id="tr_{{$role->id}}">
                                    <td>{{ $role->id }}</td>
                                    <td><span class="text-ellipsis">{{ $role->name }}</span></td>
                                    <td><span class="text-ellipsis">{{ $role->description }}</span></td>
                                    <td>
                                        <a href="{{ route('roles.edit', ['role_id' => $role->id]) }}"
                                           class="btn btn-primary">Edit</a>
                                    </td>
                                    <td>
                                    <td>
                                        <a href="javascript:void(0)" onclick="deleteItem({{$role->id}}, 'roles')"
                                           class="btn btn-danger delete-role">Delete</a>
                                    </td>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5">No roles available.</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                @endif

                <footer class="panel-footer">
                    <div class="row">
                        <div class="col-sm-7 text-right text-center-xs">
                            <ul class="pagination pagination-sm m-t-none m-b-none">
                                @if ($roles->onFirstPage())
                                    <li class="disabled"><span>&laquo;</span></li>
                                @else
                                    <li><a href="{{ $roles->previousPageUrl() }}" rel="prev">&laquo;</a></li>
                                @endif
                                @for ($i = 1; $i <= $roles->lastPage(); $i++)
                                    <li class="{{ ($roles->currentPage() == $i) ? 'active' : '' }}">
                                        <a href="{{ $roles->url($i) }}">{{ $i }}</a>
                                    </li>
                                @endfor
                                @if ($roles->hasMorePages())
                                    <li><a href="{{ $roles->nextPageUrl() }}" rel="next">&raquo;</a></li>
                                @else
                                    <li class="disabled"><span>&raquo;</span></li>
                                @endif
                            </ul>
                        </div>
                    </div>
                </footer>

            </div>
        </div>
@endsection