routes/web.php
<?php

use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Route::resource('roles', RoleController::class);
    Route::prefix('roles')->middleware('roles:super-admin')->controller(RoleController::Class)->name('roles.')->group(
        function () {
            Route::get('/', 'index')->name('index');
            Route::post('/', 'store')->name('store');
            Route::get('/create', 'create')->name('create');
            Route::get('/{role_id}', 'show')->name('show');
            Route::put('/{role_id}', 'update')->name('update');
            Route::delete('/{role_id}', 'destroy')->name('destroy');
            Route::get('/edit/{role_id}', 'edit')->name('edit');
        }
    );
    // Route::resource('users', UserController::class);
    Route::prefix('users')->controller(UserController::Class)->name('users.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('can:show-user');
        Route::post('/', 'store')->name('store')->middleware('can:create-user');
        Route::get('/create', 'create')->name('create')->middleware('can:create-user');
        Route::get('/{user_id}', 'show')->name('show')->middleware('can:show-user');
        Route::put('/{user_id}', 'update')->name('update')->middleware('can:update-user');
        Route::delete('/{user_id}', 'destroy')->name('destroy')->middleware('can:delete-user');
        Route::get('/edit/{user_id}', 'edit')->name('edit')->middleware('can:update-user');
    });
    // Route::resource('categories', CategoryController::class);
    Route::prefix('categories')->controller(CategoryController::Class)->name('categories.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('can:show-category');
        Route::post('/', 'store')->name('store')->middleware('can:create-category');
        Route::get('/create', 'create')->name('create')->middleware('can:create-category');
        Route::get('/{category_id}', 'show')->name('show')->middleware('can:show-category');
        Route::put('/{category_id}', 'update')->name('update')->middleware('can:update-category');
        Route::delete('/{category_id}', 'destroy')->name('destroy')->middleware('can:delete-category');
        Route::get('/edit/{category_id}', 'edit')->name('edit')->middleware('can:update-category');
    });
    // Route::resource('products', ProductController::class);
    Route::prefix('products')->controller(ProductController::Class)->name('products.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('can:show-product');
        Route::post('/', 'store')->name('store')->middleware('can:create-product');
        Route::get('/create', 'create')->name('create')->middleware('can:create-product');
        Route::get('/{product_id}', 'show')->name('show')->middleware('can:show-product');
        Route::put('/{product_id}', 'update')->name('update')->middleware('can:update-product');
        Route::delete('/{product_id}', 'destroy')->name('destroy')->middleware('can:delete-product');
        Route::get('/edit/{product_id}', 'edit')->name('edit')->middleware('can:update-product');
    });
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
});
Auth::routes();
    Route::controller(ForgotPasswordController::class)->group(function () {
        Route::get('forget-password', 'showForgetPasswordForm')->name('forget.password.get');
        Route::post('forget-password', 'sendMail')->name('forget.password.post');
        Route::get('reset-password/{token}', 'showResetPasswordForm')->name('reset.password.get');
        Route::post('reset-password', 'resetPassword')->name('reset.password.post');
    });

    Route::controller(RegisterController::class)->group(function () {
        Route::get('create-password/{token}','showCreatePasswordForm')->name('create.password.get');
        Route::post('create-password','createPassword')->name('create.password.post');
    });

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $fillable = ['name','parent_id'];
    public function product()
    {
        return $this->belongsToMany(Product::class,'category_product','categories_id','product_id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use App\Services\CategoryService;
use App\Services\ProductService;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    private $categoryService;

    public function __construct(CategoryService $categoryService, ProductService $productService)
    {
        $this->categoryService = $categoryService;
        $this->productService = $productService;
    }

    public function index()
    {
        $categories = $this->categoryService->paginateCategory(10);
        return view('admin.category.index', compact('categories'));
    }

    public function create()
    {
        $products = $this->productService->getAllProducts();
        return view('admin.category.create',compact('products'));
    }

    public function store(CategoryRequest $request)
    {
        $dataCategory = $request->all();
        $this->categoryService->createCategory($dataCategory);
        return redirect()->route('categories.index')->with('success', 'Category created successfully');
    }

    public function edit($category_id)
    {
        try {
            $this->categoryService->getAndCheckCategoryById($category_id);
            $data = $this->categoryService->getDataCategroyEdit($category_id);
            return view('admin.category.edit', $data);
        } catch (ModelNotFoundException $e) {
            abort(404, 'Category not found');
        }
    }

    public function update($category_id, CategoryRequest $request)
    {
        try {
            $this->categoryService->getAndCheckCategoryById($category_id);
            $dataCategory = $request->all();
            $this->categoryService->updateCategory($category_id, $dataCategory);
            return redirect()->route('categories.index')->with('success', 'Category updated successfully.');
        } catch (ModelNotFoundException $e) {
            abort(404, 'Category not found');
        }
    }

    public function destroy($category_id)
    {
        try {
            $this->categoryService->getAndCheckCategoryById($category_id);
            $this->categoryService->deleteCategory($category_id);
            return response()->json(['success' => true, 'tr' => 'tr_' . $category_id]);
        } catch (ModelNotFoundException $e) {
            abort(404, 'Category not found');
        }
    }

}

resources/views/admin/category/create.blade.php
@extends('admin.layout')
@section('content')
    <section class="panel">
        <header class="panel-heading">
            Create Category
        </header>
        <div class="panel-body">
            @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            @if(session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="form">
                <form class="cmxform form-horizontal" id="commentForm" method="post" enctype="multipart/form-data"
                      action="{{ route('categories.store') }}" novalidate="novalidate">
                    @csrf
                    <div class="form-group">
                        <label for="cname" class="control-label col-lg-3">Name </label>
                        <div class="col-lg-6">
                            <input class="form-control" id="cname" name="name" minlength="2" value="{{ old('name') }}"
                                   type="text" required="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="curl" class="control-label col-lg-3">Product</label>
                        <div class="col-lg-6">
                            <select name="products[]" class="form-control select2_init" multiple>
                                @foreach($products as $product)
                                    <option
                                        value="{{ $product->id }}" {{ in_array($product->id, old('products', [])) ? 'selected' : '' }}>
                                        {{ $product->name }}
                                    </option>
                                @endforeach
                            </select>

                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-3 col-lg-6">
                            <button class="btn btn-primary" type="submit">Save</button>
                            <button class="btn btn-default" type="button">Cancel</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/category/edit.blade.php
<!-- resources/views/admin/products/edit.blade.php -->

@extends('admin.layout')
@section('content')
    <section class="panel">
        <header class="panel-heading">
            Edit Category
        </header>
        <div class="panel-body">
            @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            @if(session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="form">
                <form class="cmxform form-horizontal" id="commentForm" method="post" enctype="multipart/form-data"
                      action="{{ route('categories.update', $category->id) }}" novalidate="novalidate">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="cname" class="control-label col-lg-3">Name </label>
                        <div class="col-lg-6">
                            <input class="form-control" id="cname" name="name" minlength="2" type="text"
                                   value="{{ old('name',$category->name) }}" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="curl" class="control-label col-lg-3">Product</label>
                        <div class="col-lg-6">
                            <select name="products[]" class="form-control select2_init" multiple>
                                @foreach($products as $product)
                                    <option
                                            {{ (collect(old('products', $productOfCategory->pluck('id')))->contains($product->id)) ? 'selected' : '' }}
                                            value="{{ $product->id }}">{{ $product->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-3 col-lg-6">
                            <button class="btn btn-primary" type="submit">Update</button>
                            <a href="{{ route('categories.index') }}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/category/index.blade.php
@extends('admin.layout')
@section('content')

    <section class="wrapper">
        <div class="table-agile-info">
            <div class="panel panel-default">
                <div class="panel-heading">
                    List Category
                </div>
                <div class="table-responsive">
                    @if(session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif
                    @if(session('error'))
                        <div class="alert alert-danger">
                            {{ session('error') }}
                        </div>
                    @endif
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <table class="table table-striped b-t b-light">
                        <thead>
                        <tr>

                            <th> ID</th>
                            <th> Name</th>

                        </tr>
                        </thead>
                        <tbody>
                        @foreach($categories as $category)
                            <tr id="tr_{{$category->id}}">
                                <td>{{$category->id}}</td>
                                <td><span class="text-ellipsis">{{ $category->name }}</span></td>
                                @can('update-category')
                                    <td>
                                        <a href="{{ route('categories.edit', ['category_id' => $category->id]) }}"
                                           class="btn btn-primary">Edit</a>
                                    </td>
                                @endcan
                                @can('delete-category')
                                    <td>
                                        <a href="javascript:void(0)" onclick="deleteItem({{$category->id}}, 'categories')"
                                           class="btn btn-danger delete-category">Delete</a>
                                    </td>
                                @endcan
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <footer class="panel-footer">
                    <div class="row">
                        <div class="col-sm-7 text-right text-center-xs">
                            <ul class="pagination pagination-sm m-t-none m-b-none">
                                @if ($categories->onFirstPage())
                                    <li class="disabled"><span>&laquo;</span></li>
                                @else
                                    <li><a href="{{ $categories->previousPageUrl() }}" rel="prev">&laquo;</a></li>
                                @endif
                                @for ($i = 1; $i <= $categories->lastPage(); $i++)
                                    <li class="{{ ($categories->currentPage() == $i) ? 'active' : '' }}">
                                        <a href="{{ $categories->url($i) }}">{{ $i }}</a>
                                    </li>
                                @endfor
                                @if ($categories->hasMorePages())
                                    <li><a href="{{ $categories->nextPageUrl() }}" rel="next">&raquo;</a></li>
                                @else
                                    <li class="disabled"><span>&raquo;</span></li>
                                @endif
                            </ul>
                        </div>
                    </div>
                </footer>

            </div>
        </div>

@endsection