routes/web.php
<?php

use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Route::resource('roles', RoleController::class);
    Route::prefix('roles')->middleware('roles:super-admin')->controller(RoleController::Class)->name('roles.')->group(
        function () {
            Route::get('/', 'index')->name('index');
            Route::post('/', 'store')->name('store');
            Route::get('/create', 'create')->name('create');
            Route::get('/{role_id}', 'show')->name('show');
            Route::put('/{role_id}', 'update')->name('update');
            Route::delete('/{role_id}', 'destroy')->name('destroy');
            Route::get('/edit/{role_id}', 'edit')->name('edit');
        }
    );
    // Route::resource('users', UserController::class);
    Route::prefix('users')->controller(UserController::Class)->name('users.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('can:show-user');
        Route::post('/', 'store')->name('store')->middleware('can:create-user');
        Route::get('/create', 'create')->name('create')->middleware('can:create-user');
        Route::get('/{user_id}', 'show')->name('show')->middleware('can:show-user');
        Route::put('/{user_id}', 'update')->name('update')->middleware('can:update-user');
        Route::delete('/{user_id}', 'destroy')->name('destroy')->middleware('can:delete-user');
        Route::get('/edit/{user_id}', 'edit')->name('edit')->middleware('can:update-user');
    });
    // Route::resource('categories', CategoryController::class);
    Route::prefix('categories')->controller(CategoryController::Class)->name('categories.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('can:show-category');
        Route::post('/', 'store')->name('store')->middleware('can:create-category');
        Route::get('/create', 'create')->name('create')->middleware('can:create-category');
        Route::get('/{category_id}', 'show')->name('show')->middleware('can:show-category');
        Route::put('/{category_id}', 'update')->name('update')->middleware('can:update-category');
        Route::delete('/{category_id}', 'destroy')->name('destroy')->middleware('can:delete-category');
        Route::get('/edit/{category_id}', 'edit')->name('edit')->middleware('can:update-category');
    });
    // Route::resource('products', ProductController::class);
    Route::prefix('products')->controller(ProductController::Class)->name('products.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('can:show-product');
        Route::post('/', 'store')->name('store')->middleware('can:create-product');
        Route::get('/create', 'create')->name('create')->middleware('can:create-product');
        Route::get('/{product_id}', 'show')->name('show')->middleware('can:show-product');
        Route::put('/{product_id}', 'update')->name('update')->middleware('can:update-product');
        Route::delete('/{product_id}', 'destroy')->name('destroy')->middleware('can:delete-product');
        Route::get('/edit/{product_id}', 'edit')->name('edit')->middleware('can:update-product');
    });
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
});
Auth::routes();
    Route::controller(ForgotPasswordController::class)->group(function () {
        Route::get('forget-password', 'showForgetPasswordForm')->name('forget.password.get');
        Route::post('forget-password', 'sendMail')->name('forget.password.post');
        Route::get('reset-password/{token}', 'showResetPasswordForm')->name('reset.password.get');
        Route::post('reset-password', 'resetPassword')->name('reset.password.post');
    });

    Route::controller(RegisterController::class)->group(function () {
        Route::get('create-password/{token}','showCreatePasswordForm')->name('create.password.get');
        Route::post('create-password','createPassword')->name('create.password.post');
    });

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Intervention\Image\Facades\Image;

class Product extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'description','price','image_path','sale'];
    public function categories()
    {
        return $this->belongsToMany(Category::class, 'category_product', 'product_id', 'categories_id');
    }
    public function getFormattedPriceAttribute()
    {
        return '$' . number_format($this->price, 2);
    }
    public function setImagePathAttribute($value)
    {
        $this->attributes['image_path'] = $this->processAndSaveImage($value);
    }
    public function getImagePathAttribute($value)
    {
        return $value;
    }
    private function processAndSaveImage($image)
    {
        if (!$image instanceof UploadedFile) {
            return null;
        }
        $imageName = time() . '.' . $image->getClientOriginalExtension();
        $image->move(public_path('uploads/products'), $imageName);
        $resizedImage = Image::make(public_path('uploads/products/' . $imageName))
            ->resize(300, 200)
            ->save(public_path('uploads/products/resized_' . $imageName));
        return 'uploads/products/' . $imageName;
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Models\Category;
use App\Models\Product;
use App\Models\User;
use App\Services\CategoryService;
use App\Services\ProductService;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;

class ProductController extends Controller
{
    private $productService;
    private $categoryService;

    public function __construct(ProductService $productService, CategoryService $categoryService)
    {
        $this->productService = $productService;
        $this->categoryService = $categoryService;
    }

    public function index(Request $request)
    {
        $minPrice = $request->input('min_price');
        $maxPrice = $request->input('max_price');
        $keyword = $request->input('keyword');
        $categories = $request->input('categories', []);
        $categoriesList = $this->categoryService->getAllCategory();
        $products = $this->productService->searchProducts($minPrice, $maxPrice, $keyword, $categories);
        return view('admin.product.index', compact('products', 'minPrice', 'maxPrice', 'keyword', 'categories','categoriesList'));
    }
    public function create()
    {
        $categories = $this->categoryService->getAllCategory();
        return view('admin.product.create', compact('categories'));
    }

    public function store(ProductRequest $request)
    {
        $dataProduct = $request->all();
        $this->productService->createProduct($dataProduct);
        return redirect()->route('products.index')->with('success', 'Product created successfully');
    }

    public function edit($product_id)
    {
        try {
            $this->productService->getAndCheckProductById($product_id);
            $data = $this->productService->getProductDataForEdit($product_id);
            return view('admin.product.edit', $data);
        } catch (ModelNotFoundException $e) {
            abort(404, 'Product not found');
        }
    }

    public function update(ProductRequest $request, $product_id)
    {
        try {
            $this->productService->getAndCheckProductById($product_id);
            $dataProduct = $request->all();
            $this->productService->updateProduct($product_id, $dataProduct);
            return redirect()->route('products.index')->with('success', 'Product updated successfully');
        } catch (ModelNotFoundException $e) {
            abort(404, 'Product not found');
        }
    }

    public function destroy($id)
    {
        try {
            $this->productService->getAndCheckProductById($id);
            $this->productService->deleteProduct($id);
            return response()->json(['success' => true, 'tr' => 'tr_' . $id]);
        } catch (ModelNotFoundException $e) {
            abort(404, 'Product not found');
        }
    }

}

resources/views/admin/product/create.blade.php
@extends('admin.layout')
@section('content')
    <section class="panel">
        <header class="panel-heading">
            Create Product
        </header>
        <div class="panel-body">
            @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            @if(session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="form">
                <form class="cmxform form-horizontal" id="commentForm" method="POST" enctype="multipart/form-data"
                      action="{{ route('products.store') }}" novalidate="novalidate">
                    @csrf
                    <div class="form-group">
                        <label for="cname" class="control-label col-lg-3">Name </label>
                        <div class="col-lg-6">
                            <input class="form-control" id="cname" name="name" minlength="2" type="text"
                                   value="{{ old('name') }}" required="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="description" class="control-label col-lg-3">Description</label>
                        <div class="col-lg-6">
                            <input class="form-control" id="cemail" type="text" name="description"
                                   value="{{ old('description') }}" required="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="curl" class="control-label col-lg-3">Sale</label>
                        <div class="col-lg-6">
                            <input class="form-control" id="curl" type="number" value="{{ old('sale') }}" name="sale">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cprice" class="control-label col-lg-3">Price</label>
                        <div class="col-lg-6">
                            <input class="form-control" id="cprice" type="number" value="{{ old('price') }}"
                                   name="price" >
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="curl" class="control-label col-lg-3">Category</label>
                        <div class="col-lg-6">
                            <select name="categories[]" class="form-control select2_init" multiple>
                                @foreach($categories as $category)
                                    <option
                                        value="{{ $category->id }}" {{ in_array($category->id, old('categories', [])) ? 'selected' : '' }}>
                                        {{ $category->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cimage" class="control-label col-lg-3">Image Path</label>
                        <div class="col-lg-6">
                            <input type="file" name="image_path"
                                   onchange="handleImageChange(this)" >
                                <img id="img-holder"  alt="your image"  class="img-responsive" width="200" height="200"  />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-3 col-lg-6">
                            <button class="btn btn-primary" type="submit">Save</button>
                            <button class="btn btn-default" type="button">Cancel</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layout')
@section('content')
    <section class="panel">
        <header class="panel-heading">
            Edit Product
        </header>
        <div class="panel-body">
            @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            @if(session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="form">
                <form class="cmxform form-horizontal" id="commentForm" method="post" enctype="multipart/form-data"
                      action="{{ route('products.update', $product->id) }}" novalidate="novalidate">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="cname" class="control-label col-lg-3">Name </label>
                        <div class="col-lg-6">
                            <input class="form-control" id="cname" name="name" minlength="2" type="text"
                                   value="{{ old('name', $product->name) }}" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cemail" class="control-label col-lg-3">Description</label>
                        <div class="col-lg-6">
                            <input class="form-control" id="cemail" type="text" name="description"
                                   value="{{ old('description', $product->description) }}" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="curl" class="control-label col-lg-3">Sale</label>
                        <div class="col-lg-6">
                            <input class="form-control" id="curl" type="number" name="sale"
                                   value="{{ old('sale', $product->sale) }}" >
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cprice" class="control-label col-lg-3">Price</label>
                        <div class="col-lg-6">
                            <input class="form-control" id="cprice" type="number" name="price"
                                   value="{{ old('price', $product->price) }}" min="0">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cimage" class="control-label col-lg-3">Image Path</label>
                        <div class="col-lg-6">
                            <input type="file" name="image_path"  onchange="handleImageChange(this)"  id="cimage" accept="image/*">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="curl" class="control-label col-lg-3">Category</label>
                        <div class="col-lg-6">
                            <select name="categories[]" class="form-control select2_init" multiple>
                                @foreach($categories as $category)
                                    <option
                                        {{ (collect(old('categories', $categoryOfProduct->pluck('id')))->contains($category->id)) ? 'selected' : '' }}
                                        value="{{ $category->id }}">{{ $category->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    @if(isset($product->image_path))
                        <div class="form-group">
                            <label class="control-label col-lg-3">Current Image</label>
                            <div class="col-lg-6">
                                <div class="img-holder">
                                    <img id="img-holder" src="{{ asset($product->image_path) }}" alt="Current Image" width="200" height="200"  >
                                </div>
                            </div>
                        </div>
                    @else
                        <div class="form-group">
                            <label class="control-label col-lg-3"></label>
                            <div class="col-lg-6">
                                <div class="img-holder">
                                    <img id="img-holder"  alt="Current Image" class="img-responsive" >
                                </div>
                            </div>
                    @endif
                    <div class="form-group">
                        <div class="col-lg-offset-3 col-lg-6">
                            <button class="btn btn-primary" type="submit">Update</button>
                            <a href="{{ route('products.index') }}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/product/index.blade.php
@extends('admin.layout')
@section('content')
    <section class="wrapper">
        <div class="table-agile-info">
            <div class="panel panel-default">
                <div class="panel-heading">
                    List Product
                </div>
                <div class="row w3-res-tb form-search">
                    <div class="col-sm-6">
                        <div class="input-group">
                            <form action="{{ route('products.index') }}" method="GET">
                                <div class="form-group">
                                    <label for="min_price">Min Price:</label>
                                    <input type="number" class="input-sm form-control" name="min_price" id="min_price"
                                           placeholder="Min Price" value="{{ $minPrice }}">
                                </div>
                                <div class="form-group">
                                    <label for="max_price">Max Price:</label>
                                    <input type="number" class="input-sm form-control" name="max_price" id="max_price"
                                           placeholder="Max Price" value="{{ $maxPrice }}">
                                </div>
                                <div class="form-group">
                                    <label for="keyword">Keyword:</label>
                                    <input type="text" class="input-sm form-control" id="keyword" placeholder="Search"
                                           name="keyword" value="{{ $keyword }}">
                                </div>
                                <div class="form-group">
                                    <label for="curl" class="control-label ">Category :</label>
                                    <select name="categories[]" class="form-control select2_init" multiple>
                                        @foreach($categoriesList as $category)
                                            <option
                                                value="{{ $category->id }}" {{ in_array($category->id, (array)request('categories', [])) ? 'selected' : '' }}>
                                                {{ $category->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-success" type="submit">Search</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            @if ($products->isEmpty())
                <div class="alert alert-info">
                    No results found.
                </div>
            @else
                <div class="table-responsive">
                    @if(session()->has('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif

                    @if(session()->has('error'))
                        <div class="alert alert-danger">
                            {{ session('error') }}
                        </div>
                    @endif

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <table class="table table-striped b-t b-light">
                        <thead>
                        <tr>
                            <th> ID</th>
                            <th> Name</th>
                            <th> Image</th>
                            <th> Description</th>
                            <th> Price</th>
                            @can('update-product')
                                <th> Edit</th>
                            @endcan
                            @can('delete-product')
                                <th> Delete</th>
                            @endcan
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($products as $product)
                            <tr id="tr_{{$product->id}}">
                                <td>{{ $product->id }}</td>
                                <td><span class="text-ellipsis">{{ $product->name }}</span></td>
                                <td>
                                    @if($product->image_path)
                                        <img src="{{ asset($product->image_path) }}" alt="{{ $product->name }}"
                                             class="image">
                                    @else
                                        No Image
                                    @endif
                                </td>
                                <td><span class="text-ellipsis">{{ $product->description }}</span></td>
                                <td><span class="text-ellipsis">{{ $product->formatted_price }}</span></td>
                                @can('update-product')
                                    <td>
                                        <a href="{{ route('products.edit', ['product_id' => $product->id]) }}"
                                           class="btn btn-primary">Edit</a>
                                    </td>
                                @endcan
                                @can('delete-product')
                                    <td>
                                        <a href="javascript:void(0)" onclick="deleteItem({{$product->id}}, 'products')"
                                           class="btn btn-danger delete-product">Delete</a>
                                    </td>
                                @endcan
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6">No products available.</td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            @endif
            <footer class="panel-footer">
                <div class="row">
                    <div class="col-sm-7 text-right text-center-xs">
                        <ul class="pagination pagination-sm m-t-none m-b-none">
                            @if ($products->onFirstPage())
                                <li class="disabled"><span>&laquo;</span></li>
                            @else
                                <li><a href="{{ $products->previousPageUrl() }}" rel="prev">&laquo;</a></li>
                            @endif
                            @for ($i = 1; $i <= $products->lastPage(); $i++)
                                <li class="{{ ($products->currentPage() == $i) ? 'active' : '' }}">
                                    <a href="{{ $products->url($i) }}">{{ $i }}</a>
                                </li>
                            @endfor
                            @if ($products->hasMorePages())
                                <li><a href="{{ $products->nextPageUrl() }}" rel="next">&raquo;</a></li>
                            @else
                                <li class="disabled"><span>&raquo;</span></li>
                            @endif
                        </ul>
                    </div>
                </div>
            </footer>

        </div>
        </div>
    </section>
@endsection