routes/web.php
<?php

use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Route::resource('roles', RoleController::class);
    Route::prefix('roles')->middleware('roles:super-admin')->controller(RoleController::Class)->name('roles.')->group(
        function () {
            Route::get('/', 'index')->name('index');
            Route::post('/', 'store')->name('store');
            Route::get('/create', 'create')->name('create');
            Route::get('/{role_id}', 'show')->name('show');
            Route::put('/{role_id}', 'update')->name('update');
            Route::delete('/{role_id}', 'destroy')->name('destroy');
            Route::get('/edit/{role_id}', 'edit')->name('edit');
        }
    );
    // Route::resource('users', UserController::class);
    Route::prefix('users')->controller(UserController::Class)->name('users.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('can:show-user');
        Route::post('/', 'store')->name('store')->middleware('can:create-user');
        Route::get('/create', 'create')->name('create')->middleware('can:create-user');
        Route::get('/{user_id}', 'show')->name('show')->middleware('can:show-user');
        Route::put('/{user_id}', 'update')->name('update')->middleware('can:update-user');
        Route::delete('/{user_id}', 'destroy')->name('destroy')->middleware('can:delete-user');
        Route::get('/edit/{user_id}', 'edit')->name('edit')->middleware('can:update-user');
    });
    // Route::resource('categories', CategoryController::class);
    Route::prefix('categories')->controller(CategoryController::Class)->name('categories.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('can:show-category');
        Route::post('/', 'store')->name('store')->middleware('can:create-category');
        Route::get('/create', 'create')->name('create')->middleware('can:create-category');
        Route::get('/{category_id}', 'show')->name('show')->middleware('can:show-category');
        Route::put('/{category_id}', 'update')->name('update')->middleware('can:update-category');
        Route::delete('/{category_id}', 'destroy')->name('destroy')->middleware('can:delete-category');
        Route::get('/edit/{category_id}', 'edit')->name('edit')->middleware('can:update-category');
    });
    // Route::resource('products', ProductController::class);
    Route::prefix('products')->controller(ProductController::Class)->name('products.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('can:show-product');
        Route::post('/', 'store')->name('store')->middleware('can:create-product');
        Route::get('/create', 'create')->name('create')->middleware('can:create-product');
        Route::get('/{product_id}', 'show')->name('show')->middleware('can:show-product');
        Route::put('/{product_id}', 'update')->name('update')->middleware('can:update-product');
        Route::delete('/{product_id}', 'destroy')->name('destroy')->middleware('can:delete-product');
        Route::get('/edit/{product_id}', 'edit')->name('edit')->middleware('can:update-product');
    });
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
});
Auth::routes();
    Route::controller(ForgotPasswordController::class)->group(function () {
        Route::get('forget-password', 'showForgetPasswordForm')->name('forget.password.get');
        Route::post('forget-password', 'sendMail')->name('forget.password.post');
        Route::get('reset-password/{token}', 'showResetPasswordForm')->name('reset.password.get');
        Route::post('reset-password', 'resetPassword')->name('reset.password.post');
    });

    Route::controller(RegisterController::class)->group(function () {
        Route::get('create-password/{token}','showCreatePasswordForm')->name('create.password.get');
        Route::post('create-password','createPassword')->name('create.password.post');
    });

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
        'country_code',
        'region_code',
        'national_number',
        'e164_format'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = ['email_verified_at' => 'datetime'];
    protected static function boot()
    {
        parent::boot();

        static::created(function ($user) {
            if ($user->roles->isEmpty()) {
                // 5 is role id user
                $defaultRole = Role::find(5);
                if ($defaultRole) {
                    $user->roles()->attach($defaultRole);
                }
            }
        });
    }
    public function hasRole(string $role)
    {
        return $this->roles()->where('name', $role)->exists();
    }


    public function hasAnyRoles(array $roles)
    {
        if (is_array($roles)) {
            foreach ($roles as $role) {
                if ($this->hasRole($role)) {
                    return true;
                }
            }
        }
        return false;
    }
    public function roles()
    {
        return $this->belongsToMany(Role::class,'user_role','user_id','role_id');
    }
    public function  checkPermissionAccess( $permissionCheck )
    {
        $roles = auth()->user()->roles;
        foreach ($roles as $role) {
            $permissions = $role->permissions;
            if ($permissions->contains('name',$permissionCheck)) {
                return true;
            }
        }
        return false;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RegisterRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Models\Role;
use App\Models\User;
use App\Services\PermissionService;
use App\Services\ProductService;
use App\Services\CategoryServiceInterface;
use App\Services\RoleService;
use App\Services\UserService;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    private $userService;
    private $roleService;

    public function __construct(UserService $userService, RoleService $roleService)
    {
        $this->userService = $userService;
        $this->roleService = $roleService;
    }

    public function index(Request $request)
    {
        $keyword = $request->input('keyword', '');
        $users = $this->userService->searchUsers($keyword);
        return view('admin.user.index', compact('users', 'keyword'));
    }

    public function create()
    {
        $roles = $this->roleService->getAllRoles();
        return view('admin.user.create', compact('roles'));
    }

    public function store(RegisterRequest $request)
    {
        $dataUser = $request->all();
        $this->userService->createUser($dataUser);
        return redirect()->route('users.index')->with('success', 'User created successfully. ');
    }

    public function edit($user_id)
    {
        try {
            $this->userService->getAndCheckUserById($user_id);
            $data = $this->userService->getUserDataForEdit($user_id);
            return view('admin.user.edit', $data);
        } catch (ModelNotFoundException $e) {
            abort(404, 'User not found');
        }
    }

    public function update(UserUpdateRequest $request, $user_id)
    {
        try {
            $this->userService->getAndCheckUserById($user_id);
            $dataUser = $request->all();
            $this->userService->updateUser($user_id, $dataUser);
            return redirect()->route('users.index')->with('success', 'User updated successfully.');
        } catch (ModelNotFoundException $e) {
            abort(404, 'User not found');
        }
    }

    public function destroy($user_id)
    {
        try {
            $this->userService->getAndCheckUserById($user_id);
            $this->userService->deleteUser($user_id);
            return response()->json(['success' => true, 'tr' => 'tr_' . $user_id]);
        } catch (ModelNotFoundException $e) {
            abort(404, 'User not found');
        }
    }

}

resources/views/admin/user/create.blade.php
@extends('admin.layout')
@section('content')
    <section class="panel">
        <header class="panel-heading">
            Create User
        </header>
        <div class="panel-body">
            @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            <!-- Add error message -->
            @if(session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="form">
                <form class="cmxform form-horizontal" id="commentForm" method="post" action="{{ route('users.store') }}"
                      novalidate="novalidate">
                    @csrf
                    <div class="form-group">
                        <label for="cname" class="control-label col-lg-3">Name </label>
                        <div class="col-lg-6">
                            <input class="form-control" id="cname" name="name" minlength="2" type="text"
                                   value="{{ old('name') }}" required="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="control-label col-lg-3">E-Mail</label>
                        <div class="col-lg-6">
                            <input class="form-control" id="cemail" type="email" name="email" value="{{ old('email') }}"
                                   required="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="curl" class="control-label col-lg-3">Phone</label>
                        <div class="col-lg-6">
                            <input class="form-control phone-number" placeholder="" id="phone" type="tel" value="{{ old('phone') }}"
                                   name="phone">
                            <input type="hidden" name="region_code" id="region_code" value="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="curl" class="control-label col-lg-3">Password</label>
                        <div class="col-lg-6">
                            <input class="form-control" id="curl" type="password" name="password">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="curl" class="control-label col-lg-3">Role</label>
                        <div class="col-lg-6">
                            <select name="roles[]" class="form-control select2_init" multiple>
                                @foreach($roles as $role)
                                    <option value="{{$role->id}}"
                                            @if(in_array($role->id, old('roles', []))) selected @endif>{{$role->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-3 col-lg-6">
                            <button class="btn btn-primary" id="submit-btn" onclick="updateRegionCodes(iti2)"  type="submit">Save</button>
                            <button class="btn btn-default " type="button">Cancel</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layout')
@section('content')
    <section class="panel">
        <header class="panel-heading">
            Edit User
        </header>
        <div class="panel-body">
            @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            <!-- Add error message -->
            @if(session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>
        <div class="form">
            <form class="cmxform form-horizontal" id="commentForm" method="post"
                  action="{{ route('users.update',['user_id' => $user->id]) }}" novalidate="novalidate">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="cname" class="control-label col-lg-3">Name (required)</label>
                    <div class="col-lg-6">
                        <input class="form-control" id="cname" name="name" minlength="2"
                               value="{{old('name',$user->name)}}" type="text" required="">
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="control-label col-lg-3">E-Mail (required)</label>
                    <div class="col-lg-6">
                        <input class="form-control" id="cemail" type="email" name="email"
                               value="{{ old('email',$user->email)}}" required="">
                    </div>
                </div>
                <div class="form-group">
                    <label for="curl" class="control-label col-lg-3">Phone</label>
                    <div class="col-lg-6">
                        <input class="form-control phone-number" id="phone-update"  placeholder="" pattern="[0-9]{10}" type="tel" value="{{ old('phone',$user->phone) }}"
                               name="phone">
                        <input type="hidden" name="region_code" id="region_code" value="">
                        <input type="hidden" id="user-region-code-input" value="{{ $user->region_code ?? 'auto' }}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="curl" class="control-label col-lg-3">Password</label>
                    <div class="col-lg-6">
                        <input class="form-control" id="curl" type="password" name="password">
                    </div>
                </div>
                <div class="form-group">
                    <label for="curl" class="control-label col-lg-3">Role</label>
                    <div class="col-lg-6">
                        <select name="roles[]" class="form-control select2_init" multiple>
                            @foreach($roles as $role)
                                <option
                                    {{ (collect(old('roles', $roleOfUser->pluck('id')))->contains($role->id)) ? 'selected' : '' }}
                                    value="{{ $role->id }}">{{ $role->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-offset-3 col-lg-6">
                        <button class="btn btn-primary" id="submit-btn"  onclick="updateRegionCodes(iti1)"  type="submit">Save</button>
                        <button class="btn btn-default" type="button">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
        </div>
    </section>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layout')
@section('content')

    <section class="wrapper">
        <div class="table-agile-info">
            <div class="panel panel-default">
                <div class="panel-heading">
                    List Users
                </div>
                <div class="row w3-res-tb">
                    <div class="col-sm-4">
                    </div>
                    <div class="col-sm-3 search-key">
                        <div class="input-group">
                            <form action="{{ route('users.index') }}" method="GET">
                                <input type="text" class="input-sm form-control" placeholder="Search" name="keyword"
                                       value="{{ $keyword }}">
                                <div class="input-group-btn">
                                    <button class="btn btn-sm btn-default" type="submit">Search</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    @if(session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif

                    <!-- Add error message -->
                    @if(session('error'))
                        <div class="alert alert-danger">
                            {{ session('error') }}
                        </div>
                    @endif
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <table class="table table-striped b-t b-light">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th style="width: 30px;"></th>
                            <th style="width: 30px;"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @if ($users->isEmpty())
                            <tr>
                                <td colspan="6">
                                    <div class="alert alert-info">
                                        No results found for keyword: {{ $keyword }}
                                    </div>
                                </td>
                            </tr>
                        @else
                            @foreach($users as $user)
                                <tr id="tr_{{$user->id}}">
                                    <td>{{$user->id}}</td>
                                    <td><span class="text-ellipsis">{{$user->name}}</span></td>
                                    <td><span class="text-ellipsis">{{$user->email}}</span></td>
                                    <td><span class="text-ellipsis">{{$user->e164_format}}</span></td>
                                    @can('update-user')
                                        <td>
                                            <a href="{{ route('users.edit', ['user_id' => $user->id]) }}"
                                               class="btn btn-primary">Edit</a>
                                        </td>
                                    @endcan
                                    @can('delete-user')
                                        <td>
                                            <a href="javascript:void(0)" onclick="deleteItem({{$user->id}}, 'users')"
                                               class="btn btn-danger delete-user">Delete</a>
                                        </td>
                                    @endcan
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
                <footer class="panel-footer">
                    <div class="row">
                        <div class="col-sm-7 text-right text-center-xs">
                            <ul class="pagination pagination-sm m-t-none m-b-none">
                                @if ($users->onFirstPage())
                                    <li class="disabled"><span>&laquo;</span></li>
                                @else
                                    <li><a href="{{ $users->previousPageUrl() }}" rel="prev">&laquo;</a></li>
                                @endif
                                @for ($i = 1; $i <= $users->lastPage(); $i++)
                                    <li class="{{ ($users->currentPage() == $i) ? 'active' : '' }}">
                                        <a href="{{ $users->url($i) }}">{{ $i }}</a>
                                    </li>
                                @endfor
                                @if ($users->hasMorePages())
                                    <li><a href="{{ $users->nextPageUrl() }}" rel="next">&raquo;</a></li>
                                @else
                                    <li class="disabled"><span>&raquo;</span></li>
                                @endif
                            </ul>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
    </section>

@endsection